# Mathmatic operation using numpy

In [1]:
import numpy as np

In [3]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [4]:
arr1+arr2  #direct methode

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [5]:
np.add(arr1,arr2) #using operator

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [6]:
arr1-arr2

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [7]:
np.subtract(arr1,arr2)

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [8]:
arr1/arr2

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [9]:
np.divide(arr1,arr2)

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

In [10]:
arr1*arr2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [12]:
np.multiply(arr1,arr2)

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [13]:
arr1@arr2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [14]:
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [15]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr1.max()

9

In [18]:
arr1.argmax()

8

In [22]:
arr1.max(axis = 0) # To check max value in each coloumn


array([7, 8, 9])

In [23]:
arr1.max(axis = 1) # To check max value in each row

array([3, 6, 9])

In [24]:
arr1.min() #TO check minimum value


1

In [26]:
arr1.argmin()

0

In [27]:
arr1.min(axis = 0) #To check minimum value in each coloumn

array([1, 2, 3])

In [28]:
arr1.min(axis = 1) # To check minimum value in each row

array([1, 4, 7])

In [29]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.sum(arr1) # To check sum of all element of given matrix

45

In [31]:
np.sum(arr1, axis=0) # TO check sum of all elements of coloumn

array([12, 15, 18])

In [32]:
np.sum(arr1, axis=1) # TO check sum of all elements of row

array([ 6, 15, 24])

In [33]:
np.mean(arr1)  # TO check mean of matrix

5.0

In [34]:
np.sqrt(arr1) # TO find sqrt of each element 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [35]:
np.std(arr1) # TO find standard division of matrix 

2.581988897471611

In [36]:
np.exp(arr1) # to find exponent of each element

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [37]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [38]:
np.log10(arr1) # To find log to base 10 

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])