In [3]:
import numpy as np

In [4]:
array_1d=np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [5]:
type(array_1d)

numpy.ndarray

In [6]:
array_1d.ndim

1

In [10]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])

print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
arr_2d.ndim

2

In [13]:
arr_2d.size

8

In [14]:
arr_2d.shape

(2, 4)

In [15]:
arr_2d.dtype

dtype('int32')