In [1]:
import numpy as np

In [3]:
mx_1=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [8]:
mx_1s.dtype

dtype('float64')

In [10]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
mx_0s=np.zeros((3,4),dtype=int)
print(mx_0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [14]:
mx_0s=np.zeros((3,4),dtype=bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [16]:
mx_1s=np.ones((3,4),dtype=bool)
print(mx_1s)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [17]:
mx_1s=np.ones((3,4),dtype=str)
print(mx_1s)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [19]:
mx_0s=np.zeros((3,4),dtype=str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


em_mx=np.empty((3,3))
print(em_mx)

In [20]:
em_mx=np.empty((3,3))
print(em_mx)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 7.075e-321]
 [0.000e+000 0.000e+000 0.000e+000]]
