In [1]:
# Numpy function: 

#  Numpy Function



# arange()

In [9]:
import numpy as np

In [17]:
#np.arange(start ,Ende, steps)
arr_1d=np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
even_arr=np.arange(1,13,2)
print(even_arr)

[ 1  3  5  7  9 11]


# linspace


In [22]:
np.linspace(1,13,5)

array([ 1.,  4.,  7., 10., 13.])

# reshape()

In [24]:
arr_2d=arr_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [25]:
arr_3d=arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
arr=np.arange(1,13).reshape(2,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [27]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [28]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transpose()

In [30]:
arr.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [32]:
arr.T #transpose shortcut

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])